- name: Pull hadoop base image
  community.docker.docker_image:
    name: "{{ registry_domain }}:{{ registry_port }}/hadoop2-base:latest"
    source: pull

- name: Start Hadoop slaves
  shell: |
    docker run -itd \
        --net=private-cloud \
        --name hadoop-slave{{ item.slave_id }} \
        --hostname hadoop-slave{{ item.slave_id }} \
        {{ registry_domain }}:{{ registry_port }}/hadoop2-base:latest
  with_items:
    - { slave_id: 1, inventory_hostname: "lxc1" }
    - { slave_id: 2, inventory_hostname: "lxc3" }
  when: inventory_hostname == item.inventory_hostname