---
- name: Download duckdns-update package
  get_url:
    url: "https://gitlab.com/api/v4/projects/53136153/packages/generic/duckdns-update/0.1.0/duckdns-update_0.1.0.tar.xz"
    dest: "/tmp/duckdns-update_0.1.0.tar.xz"
- name: Install duckdns-update
  become: yes
  unarchive:
    src: "/tmp/duckdns-update_0.1.0.tar.xz"
    dest: "/"
    remote_src: yes
- name: Configure duckdns-update
  copy:
    src: "../files/duckdns-update.conf"
    dest: "/usr/local/etc/duckdns-update.conf"
- name: Start duckdns-update timer
  become: yes
  systemd_service:
    name: "duckdns-update.timer"
    state: "started"
    enabled: true
