---
- name: Create docker client certificate folder
  file:
    path: "/etc/docker/certs.d/registry.datuen-ingenieritza.local:5000"
    state: "directory"
- name: Copy ca.crt
  copy:
    src: "../files/certificates/ca.crt"
    dest: "/etc/docker/certs.d/registry.datuen-ingenieritza.local:5000"
- name: Copy client.cert
  copy:
    src: "../files/certificates/client.cert"
    dest: "/etc/docker/certs.d/registry.datuen-ingenieritza.local:5000"
- name: Copy client.key
  copy:
    src: "../files/certificates/client.key"
    dest: "/etc/docker/certs.d/registry.datuen-ingenieritza.local:5000"
- name: Add necessary route on /etc/hosts
  shell: "echo \"{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }} registry.datuen-ingenieritza.local\" >> /etc/hosts"
# - name: Copy daemon.json
#   copy:
#     src: "../files/daemon.json"
#     dest: "/etc/docker/daemon.json"
- name: Restart Docker service
  systemd:
    name: "docker"
    state: "restarted"