#!/bin/sh

# Hemen bukatu diren tofu komandoak gehitzen joan
# Adibidez: 
# tofu init && tofu apply makina1/

# Prozesuen PID lista
PIDS=""

echo "Creating infraestructure...."
echo ""

# echo "###############################"
# echo "####### SonarQube #############"
# echo "###############################"
# cd ../sonarqube; tofu init; tofu apply -auto-approve

# sleep 1

# echo "###############################"
# echo "####### REVERSE PROXY #########"
# echo "###############################"
# cd reverse-proxy; tofu init; tofu apply -auto-approve &
# PIDS="$PIDS $!"

# Itxaron prozesu guztiak bukatzea
wait $PIDS