---
- name: Create a Docker container
  become: yes
  docker_container:
    name: sonarqube
    image: sonarqube:community
    state: started
    detach: true
    hostname: "sonarqube"
    ports:
      - "9000:9000"
    volumes:
      - "sonarqube_data:/opt/sonarqube/data"
      - "sonarqube_extensions:/opt/sonarqube/extensions"
      - "sonarqube_logs:/opt/sonarqube/logs"

