- name: Create volume directory
  file:
    path: "/etc/cassandra"
    state: directory
- name: Create a volume for Cassandra data
  become: yes
  docker_volume:
    name: cassandra-data
    driver_options:
      type: none
      device: "/etc/cassandra"
      o: bind