- name: Create a Cassandra Docker container
  become: yes
  docker_container:
    name: cassandra
    image: cassandra:latest
    state: started
    detach: true
    hostname: "cassandra"
    auto_remove: true
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - /home/user/cassandra.yaml:/etc/cassandra/cassandra.yaml
    env:
      CASSANDRA_BROADCAST_ADDRESS: "{{ ansible_default_ipv4.address }}"
      CASSANDRA_SEEDS: "node1.c.pbl6-422712.internal"

