- name: Pull Confluent Schema Registry Image
  community.docker.docker_image:
    name: "confluentinc/cp-schema-registry:7.3.0"
    source: pull

- name: Start Schema Registry
  shell: |
    docker run -d --name=schema-registry -p 8081:8081 --network private-cloud \
      -e SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka1:9092,PLAINTEXT://kafka2:9092,PLAINTEXT://kafka3:9092 \
      -e SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081 \
      -e SCHEMA_REGISTRY_HOST_NAME=schema-registry \
      confluentinc/cp-schema-registry:7.3.0
