---
- name: Setup Hadoop Slaves
  hosts: slaves
  remote_user: root
  roles:
    - hadoop_cluster_slaves

- name: Setup Hadoop Master
  hosts: master
  remote_user: root
  roles:
    - hadoop_cluster_master
