- name: Start Kafka Broker container
  shell: |
    docker run -d --name kafka{{ item.broker_id }} \
      -p {{ item.port }}:29092 \
      -p 9092:9092 \
      -p 8083:8083 \
      --env ZOOKEEPER_HOST=zookeeper \
      --env ZOOKEEPER_PORT=2181 \
      --env BROKER_ID={{ item.broker_id }} \
      --network private-cloud \
      {{ registry_domain }}:{{ registry_port }}/kafka:latest \
      bash -c "./run_start_server.sh && bin/connect-distributed.sh config/connect-distributed.properties"
  with_items:
    - { broker_id: 1, port: 29092, inventory_hostname: "lxc1" }
    - { broker_id: 2, port: 29093, inventory_hostname: "lxc2" }
    - { broker_id: 3, port: 29094, inventory_hostname: "lxc3" }
  when: inventory_hostname == item.inventory_hostname


- name: Execute connect-distributed.sh inside Kafka container
  shell: "docker exec -d kafka{{ item.broker_id }} bin/connect-distributed.sh config/connect-distributed.properties"
  with_items:
    - { broker_id: 1, inventory_hostname: "lxc1" }
    - { broker_id: 2, inventory_hostname: "lxc2" }
    - { broker_id: 3, inventory_hostname: "lxc3" }
  when: inventory_hostname == item.inventory_hostname